packages:
  - apps/*
  - packages/**
  - tooling/*
catalog:
  "@babel/core": ^7.26.0
  "@expo/vector-icons": ^14.0.2
  "@hookform/resolvers": ^3.9.1
  "@manypkg/cli": ^0.23.0
  "@react-native-async-storage/async-storage": ^2.1.0
  "@react-navigation/native": ^7.0.14
  "@rn-primitives/accordion": ^1.1.0
  "@rn-primitives/alert-dialog": ^1.1.0
  "@rn-primitives/avatar": ^1.1.0
  "@rn-primitives/checkbox": ^1.1.0
  "@rn-primitives/collapsible": ^1.1.0
  "@rn-primitives/dialog": ^1.1.0
  "@rn-primitives/dropdown-menu": ^1.1.0
  "@rn-primitives/hover-card": ^1.1.0
  "@rn-primitives/label": ^1.1.0
  "@rn-primitives/menubar": ^1.1.0
  "@rn-primitives/navigation-menu": ^1.1.0
  "@rn-primitives/popover": ^1.1.0
  "@rn-primitives/progress": ^1.1.0
  "@rn-primitives/radio-group": ^1.1.0
  "@rn-primitives/select": ^1.1.0
  "@rn-primitives/separator": ^1.1.0
  "@rn-primitives/slot": ^1.1.0
  "@rn-primitives/switch": ^1.1.0
  "@rn-primitives/table": ^1.1.0
  "@rn-primitives/tabs": ^1.1.0
  "@rn-primitives/toggle": ^1.1.0
  "@rn-primitives/toggle-group": ^1.1.0
  "@rn-primitives/types": ^1.1.0
  "@supabase/supabase-js": ^2.47.12
  "@tanstack/react-query": ^5.62.16
  "@trivago/prettier-plugin-sort-imports": ^5.2.1
  "@turbo/gen": ^2.3.3
  "@types/aes-js": ^3.1.4
  "@types/eslint": ^8.56.5
  "@types/jest": ^29.5.12
  "@types/node": ^22.7.5
  "@types/react": ^18.3.11
  "@types/react-dom": ^18.3.1
  "@types/react-test-renderer": 18.0.7
  "@typescript-eslint/eslint-plugin": ^8.19.1
  "@typescript-eslint/parser": ^8.19.1
  "@vercel/style-guide": ^5.2.0
  aes-js: ^3.1.2
  babel-plugin-module-resolver: 5.0.2
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  cross-env: ^7.0.3
  eslint: 8.57.0
  eslint-config-expo: ^8.0.1
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.3.3
  eslint-plugin-only-warn: ^1.1.0
  expo: ~52.0.23
  expo-auth-session: ^5.5.2
  expo-constants: ~17.0.3
  expo-dev-client: 5.0.9
  expo-document-picker: ^13.0.1
  expo-font: ~13.0.2
  expo-linking: ~7.0.3
  expo-router: ~4.0.15
  expo-secure-store: ^14.0.0
  expo-splash-screen: ~0.29.18
  expo-status-bar: ~2.0.0
  expo-system-ui: ~4.0.6
  expo-web-browser: ~14.0.1
  jest: ^29.2.1
  jest-expo: ~52.0.2
  lucide-react-native: ^0.471.0
  metro-cache: ^0.81.0
  nativewind: 4.1.23
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.8
  react: 18.3.1
  react-dom: 18.3.1
  react-hook-form: ^7.54.2
  react-is: 18.3.1
  react-native: ^0.76.5
  react-native-gesture-handler: ~2.20.2
  react-native-get-random-values: ^1.11.0
  react-native-reanimated: ~3.16.6
  react-native-safe-area-context: 4.12.0
  react-native-screens: 4.4.0
  react-native-svg: ^15.10.1
  react-native-web: ~0.19.10
  react-test-renderer: 18.2.0
  supabase: 2.6.8
  sonner: 1.7.2
  sonner-native: 0.16.2
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  turbo: ^2.3.3
  typescript: ^5.7.2
  zod: ^3.24.1
